### ISSUE TITLE
Small tasks

### ISSUE THREAD

**Issue by giladgotman** [giladgotman/celebs#28]
**Description**
Small things for lazy people who don't want to create new issues.

**Tasks**
- [ ] Remove capital letters (Your Turn Ended)
- [ ] Better deeplink copy
- [ ] better colors
- [ ] Check deep link to game + reopen from recent
